rest: gunicorn -c gunicorn_config.py wsgi
wamp: python3 -u ws.py
work: celery -A worker worker -X "${SUPERDESK_CELERY_PREFIX}publish"
beat: celery -A worker beat
work_publish: celery -A worker worker -Q "${SUPERDESK_CELERY_PREFIX}publish"
